version: "3.1"
services:
  mongo1:
    container_name: mongo1
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - 27017:27017
      - 28017:28017
    env_file:
      - .env
    volumes:
      - volume-mongo:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    command: ['--auth', '--wiredTigerCacheSizeGB=1']
    networks:
      - mongo-network
  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - '8081:8081'
  #   env_file:
  #     - .env
  #   environment:
  #     - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
  #     - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
  #     - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASS}
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
  #     - ME_CONFIG_MONGODB_SERVER=mongo1
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}
  #   depends_on:
  #     - mongo1
  #   networks:
  #     - mongo-network
volumes:
  volume-mongo:
    driver: local

networks:
  mongo-network:
    driver: bridge